version: "3.2"

services:
  app_prod:
    container_name: app_prod
    build:
      context: ./app
      args:
        REACT_APP_API_URL: ${IP_ADDRESS_PROD}
      dockerfile: Dockerfile
    restart: unless-stopped
  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/github/ssl:/ssl/
