version: "3.2"

services:
  app-prod:
    container_name: app-prod
    build:
      context: ./app
      args:
        REACT_APP_API_URL: ${IP_ADDRESS_PROD}
        REACT_APP_ENVIRONMENT: Prod
      dockerfile: Dockerfile
    restart: unless-stopped
  api-prod:
    container_name: api-prod
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/github/ssl:/ssl/
