name: Prod

on:
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules_Sync'
    runs-on: self-hosted

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: 'Cleanup build folder'
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CI_TOKEN }}

    # Update references
    - name: Git Sumbodule Update
      run: |
        git submodule update --force --recursive --init --remote
        
    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
        
  build:
    runs-on: self-hosted
    needs: sync
    env:
      DB_PASSWORD_PROD: ${{ secrets.DB_PASSWORD_PROD }}
      IP_ADDRESS_PROD: ${{ secrets.IP_ADDRESS_PROD }}
      DB_PASSWORD_TEST: ${{ secrets.DB_PASSWORD_TEST }}
      IP_ADDRESS_TEST: ${{ secrets.IP_ADDRESS_TEST }}
      API_SECRET_TEST: ${{secrets.API_SECRET_TEST}}
      API_MAIL_PASSWORD_TEST: ${{secrets.API_MAIL_PASSWORD_TEST}}
      API_DB_TEST: ${{secrets.API_DB_TEST}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        ref: main
    - name: Start containers
      run: docker-compose -f "docker-compose-prod.yml" up -d --build
