name: CI/CD PROD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      DB_PASSWORD_PROD: ${{ secrets.DB_PASSWORD_PROD }}
      IP_ADDRESS_PROD: ${{ secrets.IP_ADDRESS_PROD }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Start containers
      run: docker-compose -f "docker-compose-prod.yml" up -d --build
