name: CI/CD TEST

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      DB_PASSWORD_TEST: ${{ secrets.DB_PASSWORD_TEST }}
      IP_ADDRESS_TEST: ${{ secrets.IP_ADDRESS_TEST }}
      API_SECRET_TEST: ${{secrets.API_SECRET_TEST}}
      API_DB_TEST: ${{secrets.API_DB_TEST}}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Pull & update submodules recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    - name: Start containers
      run: docker-compose -f "docker-compose-test.yml" up -d --build
